### ISSUE TITLE
About using fMRI data or fMRI time series to calculate dynamic functional connections

### ISSUE THREAD

**Issue by Baby-Baby** [makism/dyfunconn#12] opened 2019-04-12 09:30 UTC
I would like to ask, can ‘tvfcg_ts’ be used in the time series of fMRI? If so, is the parameter 'n_channels' equivalent to the ‘number of ROIs’ in the fMRI time series, and is 'n_samples' equivalent to 'slice' in the fMRI time series, and other parameters such as ‘fb’, 'fs', etc. how to set?

**Comment by stdimitr** [comment] 2019-04-13 11:12
Maki kalispera

Logika opos to eiches anaferei tha prepei na finei to filtering inside
connectivity estimators
oste na douleuei me diafora preprocessing steps kai se diafora modalities

Στις Παρ, 12 Απρ 2019 στις 10:30 π.μ., ο/η Baby-Baby <
notifications@github.com> έγραψε:

**Comment by makism** [comment] 2019-04-17 08:16
> I would like to ask, can ‘tvfcg_ts’ be used in the time series of fMRI? If so, is the parameter 'n_channels' equivalent to the ‘number of ROIs’ in the fMRI time series, and is 'n_samples' equivalent to 'slice' in the fMRI time series, and other parameters such as ‘fb’, 'fs', etc. how to set?

Unfortunately, right now it's not possible. The main issue the filtering functions embedded in the code (and thus the requirement for the parameters 'fb’ and 'fs)'. With a bit hacking this could be possible though.

We'll work to decouple these parameters. Stay tuned!

Duplicate of #11

**Closed** 2019-04-18 07:28 UTC
